---
basics:
  # log directly to console
  logToStdout: true
  # set loglevel debug|info|warn|fatal
  logLevel: debug
  # only relevant if logToStdout is false
  logFile: ./logfile.log

fileHandling:
  # Main Hotfolder that is used
  inputFolder: ./in
  # scanning interval in seconds
  scanInterval: 10
  # where should wrong files be placed?
  sortOutFolder: /tmp/notused
  # should there be exceptions to the sorting out pattern?
  ignoredFileNames: "config\\.yml$"

  # passible fileTypes
  fileTypePDF:
    contentTypeFilter: "^application\\/pdf$"
    fileNameFilter: ".*\\.pdf$"

# List can be extendet at will but with th (correct types!)
tagging:
  - tag: swisscom
    searchExpression: "Dispaly"
    additionaltags:
      - isp
  - tag: cablecom
    searchExpression: "cablecom"
    additionaltags:
      - isp